apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
spec:
  project: redis-dev

  source:
    repoURL: https://github.com/nurhaji123/redis-k8s-gitops.git
    targetRevision: main
    path: redis-app

    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: redis-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true