api:
  replicaCount: 3

  image:
    repository: ghcr.io/nurhaji123/redis-assignment-api
    tag: "f7e7bef5600c2726a8d0b22598f32c986b3561ec"
    pullPolicy: IfNotPresent

  containerPort: 8000

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  probes:
    enabled: true

  resources:
    enabled: true

  termination:
    enabled: true

  pdb:
    enabled: true

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent

  containerPort: 6379

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

  authentication:
    enabled: true

  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: ""

  probes:
    enabled: true

  resources:
    enabled: true

  termination:
    enabled: true

config:
  redisHost: redis
  redisPort: "6379"

sealedSecret:
  redisPassword: "AgC/93QKv5ov480XbHz86RcytivPJvqDDphx2McLggZKgWpigCtMQgxGTE9/PGHyVsgL4Uv8q3DlXIAZNJ9FKqbBkjKGDlmL1kxMNrm3ehRTj6/Ow4aArRR8eZwmQMYLezQ040ROMqCPIEybailqZRRkZfKuIygAlJBSF3OTxewYMBpMapQuu/hMWePU8A2fRDb3LRuc2BdoaPfD05Ghq975sArks4wXIwFSNDSBmsYpIqHUIDOw/MYogNJNRQkjZuaHHFna1XquZcwNqQ0Y6RA78AcZcxAr1zxvAEKTIaLgve+5Q+nmmLNmg/f0w++TA0A2Ywe15jIpdxncYrQPAe5XnzzkWMiwyB9U7bLYl8adpe9AyRDzSxvKWgAmHJlodkcG3ytwd8UmXzPJdUl5ZUuvThRdQ5RoYHKB4I9w/6NL8fZluDVG6Vr1rtBZHasngTx2K/BoOlbKeXlM+HcWm6ITpbUUiq0hN0FMEirfySPCrZ9y6DmRUHwTzba1TwNcssO6QMF7agDgx66I2JuQqKIWUKlt+BkykJ9lI9qH85fppteUG5BYe+xCPqdKa+PNMpYFxCvwPukjoVJ0uJQybXkspKSyQL1H48CrT3gYjayzBEKlVNOSQo0G9EeiqkeQz9uKzrTDS3XiDm4NqPTLL8Xcnez5uiSm6XsRUsGA+5OUa67oyPqNiuxeVAPeSbnrW7jasonWT/71hw=="

ingress:
  enabled: true
  className: nginx
  host: redis-prod.local
  path: /
  pathType: Prefix
