api:
  replicaCount: 3

  image:
    repository: ghcr.io/nurhaji123/redis-assignment-api
    tag: "fc56984cfa266934dc78ead55b8fb6f85de52ced"
    pullPolicy: IfNotPresent

  containerPort: 8000

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent

  containerPort: 6379

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

config:
  redisHost: redis
  redisPort: "6379"

secret:
  redisPassword: example-password

ingress:
  enabled: true
  className: nginx
  host: localhost
  path: /
  pathType: Prefix
