api:
  replicaCount: 2

  image:
    repository: ghcr.io/nurhaji123/redis-assignment-api
    tag: "f0b876080e02a967c447151a71e3f443b8c7f232"
    pullPolicy: IfNotPresent

  containerPort: 8000

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  probes:
    enabled: true

  resources:
    enabled: true

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent

  containerPort: 6379

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

  authentication:
    enabled: true

  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: ""

  probes:
    enabled: true

  resources:
    enabled: true

config:
  redisHost: redis
  redisPort: "6379"

sealedSecret:
  redisPassword: "AgBhFfQE4GBj6UUdTt4Jnagk7Shda0tcop78WPNCMUIHlYuoP+Q8MBSzG57ep8l9XquS9P1l3kUc6lQ0C6jClRVAZT4QguJlFYDqtqBuIWnWStlUWj4l03pyWGS0tV0wR3q+0NpZ+bUextjH/MvrLlOtSn+Zh2M6Cmp1Rwq2yDOtS2406hobLMwmCMIaWJiimJHWJEfU2hndp+KyXLceVvmYDKE1Auiw6ZataQOwvAQex0UBQkw7rHb+mOa1C3VAdHz9Vsd5kz0CSO+4ke/qyDpYPh1oPSbixEmiMRC5wYJecCh8AKlrDcXJ5Y5H8Pb1l0qaT4pQMiU+6BCzaXtKlKP92R/fEY5RpjWaw9/MCQm8BvaVBYFBUtyVqov7bZM/Ywp0YSlBbQ0xhuao3Ix6TND/MUtBt51oLnnjgCSyc8agmwbldszK8DhuD5U0ZQZkl0oTWG6gYdsqBKtEScmpiVoaic+9XrRCnopgugY4uk8fCemfP2YqPWXgvKFHu0RCRlxQ/87ErXY0SzyPRlrFmuaIMg/4/ojJgF4KZDwaz3K+xNJVg7X7PuYMknsp85Wfgh4wuqkf27MsiN0iXFhncSMv5zCuVU4xD0urLpFlsMU3kJGm8gb/hqdds0roxuegCB1m3yeDOQl78m0F23ZIFQ3rwMSP5UFBQn23w/6pNLjD/jnX/81ONH7xi6dPbHXXzNDj7Jcw"

ingress:
  enabled: true
  className: nginx
  host: redis-dev.local
  path: /
  pathType: Prefix
