{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: python-api-pdb
  labels:
    app: python-api
spec:
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: python-api
{{- end }}
