apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  labels:
    app: python-api

spec:
  replicas: {{ .Values.api.replicaCount }}

  selector:
    matchLabels:
      app: python-api

  template:
    metadata:
      labels:
        app: python-api

    spec:
      containers:
        - name: python-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.api.containerPort }}

          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT

            {{- if .Values.redis.authentication.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            {{- end }}

          {{- if .Values.api.resources.enabled }}
          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu | quote }}
              memory: {{ .Values.api.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.api.resources.limits.cpu | quote }}
              memory: {{ .Values.api.resources.limits.memory | quote }}
          {{- end }}

          {{- if .Values.api.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.probes.readiness.path }}
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.api.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.api.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.api.probes.readiness.successThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.api.probes.liveness.path }}
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.api.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.api.probes.liveness.failureThreshold }}
          {{- end }}
