apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis

spec:
  replicas: {{ .Values.redis.replicaCount }}

  {{- if .Values.redis.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      {{- if .Values.redis.termination.enabled }}
      terminationGracePeriodSeconds: {{ .Values.redis.termination.gracePeriodSeconds }}
      {{- end }}

      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          {{- if .Values.redis.authentication.enabled }}
          command:
            - /bin/sh
            - -c

          args:
            - exec redis-server --requirepass "$REDIS_PASSWORD"

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          {{- end }}

          ports:
            - containerPort: {{ .Values.redis.containerPort }}

          {{- if .Values.redis.resources.enabled }}
          resources:
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
              memory: {{ .Values.redis.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
              memory: {{ .Values.redis.resources.limits.memory | quote }}
          {{- end }}

          {{- if .Values.redis.probes.enabled }}
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                {{- if .Values.redis.authentication.enabled }}
                - REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h 127.0.0.1 -p {{ .Values.redis.containerPort }} ping | grep -q '^PONG$'
                {{- else }}
                - redis-cli -h 127.0.0.1 -p {{ .Values.redis.containerPort }} ping | grep -q '^PONG$'
                {{- end }}
            periodSeconds: {{ .Values.redis.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.startup.failureThreshold }}

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                {{- if .Values.redis.authentication.enabled }}
                - REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h 127.0.0.1 -p {{ .Values.redis.containerPort }} ping | grep -q '^PONG$'
                {{- else }}
                - redis-cli -h 127.0.0.1 -p {{ .Values.redis.containerPort }} ping | grep -q '^PONG$'
                {{- end }}
            periodSeconds: {{ .Values.redis.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.redis.probes.readiness.successThreshold }}

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                {{- if .Values.redis.authentication.enabled }}
                - REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h 127.0.0.1 -p {{ .Values.redis.containerPort }} ping | grep -q '^PONG$'
                {{- else }}
                - redis-cli -h 127.0.0.1 -p {{ .Values.redis.containerPort }} ping | grep -q '^PONG$'
                {{- end }}
            periodSeconds: {{ .Values.redis.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.liveness.failureThreshold }}
          {{- end }}

          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}

      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
      {{- end }}
