{{- if .Values.sealedSecret.redisPassword }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
spec:
  encryptedData:
    REDIS_PASSWORD: {{ .Values.sealedSecret.redisPassword | quote }}

  template:
    metadata:
      name: redis-secret
    type: Opaque
{{- end }}
